# Generated by Django 5.1.5 on 2025-01-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostruario', '0002_produto_link_imagem_alter_empresa_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='link_imagem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
