# Generated by Django 4.2.18 on 2025-01-31 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostruario', '0003_empresa_link_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='link_imagem',
            new_name='link_imagem_principal',
        ),
        migrations.AddField(
            model_name='produto',
            name='link_imagens_extras',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
